version: 0.2

phases:
  pre_build:
    commands:
      - start-dockerd

  build:
    commands:
      # prepare the release
      - git-release --prepare

      - tox -e flake8,twine

      # run unit tests
      - tox -e py36,py27 -- test/unit

      # build dummy container image
      - python3 setup.py sdist
      - cp dist/sagemaker_inference-*.tar.gz test/container/sagemaker_inference.tar.gz
      - cd test/container
      - docker build -t sagemaker-inference-toolkit-test:dummy -f Dockerfile .
      - rm sagemaker_inference.tar.gz

      # run local integration tests
      - tox -e py36,py27 -- test/integration/local

      # publish the release to github
      - git-release --publish

artifacts:
  files:
    - dist/sagemaker_inference-*.tar.gz
  name: ARTIFACT_1
  discard-paths: yes
