version: 0.2

phases:
  pre_build:
    commands:
      - start-dockerd

  build:
    commands:
      # prepare the release
      - git-release --prepare

      # run linters
      - tox -e flake8,twine,pylint

      # run format verification
      - tox -e black-check

      # run unit tests
      - tox -e py36,py27 -- test/unit

      # build dummy container
      - python3 setup.py sdist
      - cp dist/sagemaker_inference-*.tar.gz test/container/sagemaker_inference.tar.gz
      - cd test/container
      - docker build -t sagemaker-inference-toolkit-test:dummy -f dummy/Dockerfile .
      - rm sagemaker_inference.tar.gz

      # build mxnet container
      - docker build -t sagemaker-inference-toolkit-test:mxnet -f mxnet/Dockerfile .

      - cd ../..

      # run local integration tests
      - IGNORE_COVERAGE=- tox -e py36,py27 -- test/integration/local

      # publish the release to github
      - git-release --publish

artifacts:
  files:
    - dist/sagemaker_inference-*.tar.gz
  name: ARTIFACT_1
  discard-paths: yes
